server:
  port: 9000
  
spring:
  application:
    name: "api-gateway-service"
    
springdoc:
  api-docs:
    enabled: true
    path: /gateway-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /gateway-service/swagger-ui.html
    urls:
      - name: Product Service
        url: /product-service/v3/api-docs
      - name: Order Service
        url: /order-service/v3/api-docs
      - name: Inventory Service
        url: /inventory-service/v3/api-docs

# Actuator configuration        
management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      
# Resilience4j configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s